name: Bug Report
about: File a bug report
title: "[Bug] "
labels: [bug]
issue_body: true
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: markdown
  attributes:
    value: |
      #1. The bug
- type: textarea
  attributes:
    label: What is the bug?
    description: Describe the bug, what is happening?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  attributes:
    label: How to reproduce the bug?
    description: Tell us how to reproduce the bug.
    placeholder: How to reproduce the bug?
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots?
    description: You can join a screenshot if you can.
    placeholder: Drag or paste a screenshot here.
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      #2. Your computer
- type: dropdown
  attributes:
    label: Operating System
    description: What operating system are you using?
    options:
    - Windows 10
    - Windows 8.1
    - Windows 8
    - Windows 7
    - macOS
    - Linux
  validations:
    required: true
- type: input
  attributes:
    label: What is the version of the operating system?
    description: Tell us the precise version of the operating system.
    placeholder: If you are using Windows, put the build number (like 10.0.19042.804)
  validations:
    required: false
- type: input
  attributes:
    label: What is the version of the software?
    description: Tell us the precise version of the software.
    placeholder: v1.3.0.2102
  validations:
    required: true
